# Generated by Django 4.2.6 on 2023-12-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_models', models.CharField(max_length=255)),
                ('product_category', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default='default1.jpg', null=True, upload_to='image/')),
            ],
        ),
    ]
