# Generated by Django 4.2.6 on 2023-12-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_shoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
