# Generated by Django 4.2.3 on 2023-12-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0004_shoesuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='image',
        ),
    ]
