# Generated by Django 4.2.3 on 2023-12-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_remove_shoes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
