# Generated by Django 4.2.6 on 2023-12-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0006_shoes_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca', models.CharField(max_length=255)),
            ],
        ),
    ]
