# Generated by Django 4.2.6 on 2023-12-05 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0008_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='add',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoes.category'),
        ),
    ]
