# Generated by Django 4.2.6 on 2023-12-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0009_shoes_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoesuser',
            name='image',
            field=models.ImageField(blank=True, default='default1.jpg', null=True, upload_to='image/'),
        ),
    ]
