# Generated by Django 4.2.6 on 2023-11-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
    ]
